### ISSUE TITLE
Add styles to right elements

### ISSUE THREAD

**Issue by Sebastian-Fitzner** [Veams/veams-component-accordion#3]
In current state the standard icon styles `--default` doesn't work, because they are applied to the icon instead to the button. 

Solution: 

``` scss
.c-accordion--default {
    /*
    Header/ Toggle Button
    ----------------------- */
    .accordion__btn {
        color: $color-primary-medium;
        display: block;
        font-size: 2rem;
        padding: 1rem * 2.4 2rem 1rem * 2.2 2rem;
        position: relative;
        text-decoration: none;
        text-transform: uppercase;
        background-color: rgba($color-light, .8);
        margin-bottom: 2px;

        &::before,
        &::after {
            @extend %pseudo;

            transition: bottom $transition-duration/2 linear $transition-duration/2, transform $transition-duration/2 linear;
            background-color: $color-primary-medium;
            height: 2px;
            right: 20px;
            top: 50%;
            width: 30px;
        }

        &::after {
            transform: rotate(90deg);
        }

        &.is-active {
            &::after {
                transform: rotate(0deg);
            }
        }
    }

    .accordion__icon {
        position: relative;
    }

    /*
    Modifiers
    ----------------------- */
    .is-active {
    }
}
```
